sudo: false
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - coverage run -a realtime_test.py
  - coverage run -a simulate_test.py
after_success:
  - codecov