# These stocks are de-listed
DELISTED = ['AABA', 'ACETQ', 'AETI', 'AGC', 'AKP', 'ALDR', 'ALN', 'ALQA',
            'AMBR', 'AMGP', 'AMID', 'AMMA', 'ANDV', 'ANDX', 'ANWWQ', 'AOI',
            'APC', 'APF', 'APHB', 'APU', 'AQ', 'ARLZQ', 'ARRS', 'ARRY',
            'ASCMQ', 'AST', 'ASV', 'ATTU', 'AVHI', 'BEL', 'BHBK', 'BID',
            'BKS', 'BLH', 'BLMT', 'BMS', 'BNCL', 'BNGOU', 'BOJA', 'BOSXF',
            'BPL', 'BRACU', 'BRSS', 'BRSWQ', 'BT', 'BVX', 'BXEFF', 'CADC',
            'CASM', 'CAW', 'CBAK', 'CBK', 'CBLK', 'CCA', 'CCNI', 'CHAC',
            'CHKE', 'CHSP', 'CIVI', 'CJ', 'CLNS', 'CMSS', 'CMSSU', 'CMTA',
            'CRAY', 'CTRL', 'CTRV', 'CTWS', 'CUR', 'CVRS', 'CYTX', 'CZFC',
            'DATA', 'DCUD', 'DDE', 'DDOC', 'DELT', 'DFBH', 'DFRG', 'DHCP',
            'DHVW', 'DNB', 'DOVA', 'DRYS', 'DSW', 'DTRM', 'DTV', 'DWDP',
            'EAGL', 'EAGLU', 'ECYT', 'EDGE', 'EDR', 'EFII', 'EHIC', 'EIV',
            'ELLI', 'EMCI', 'EMES', 'EQGP', 'ESESD', 'ESL', 'EVJ', 'EVLV',
            'EVO', 'EVP', 'FDC', 'FELP', 'FHY', 'FLF', 'FNSR', 'FNTEU',
            'FRAC', 'FRSH', 'FSNN', 'GG', 'GGP', 'GHDX', 'GLAC', 'GLACU',
            'GNBC', 'GOV', 'GPIC', 'GSHT', 'GTYHU', 'HAIR', 'HBK', 'HEB',
            'HF', 'HFBC', 'HIFR', 'HIVE', 'HKRSQ', 'HLTH', 'HMTA', 'HPJ',
            'HYGS', 'IDTI', 'IMDZ', 'IMI', 'IMMY', 'IPOA', 'ISCA', 'ISRL',
            'ITG', 'ITUS', 'JONE', 'JSYNU', 'KAAC', 'KCAP', 'KED', 'KEYW',
            'KONE', 'KOOL', 'KPFS', 'KYE', 'LABL', 'LEXEA', 'LION', 'LLL',
            'LOGO', 'LOXO', 'LTXB', 'LXFT', 'MACQ', 'MAMS', 'MB', 'MBFI',
            'MBNAA', 'MBNAB', 'MBTF', 'MDSO', 'MFCB', 'MMDM', 'MOC', 'MPAC',
            'MRT', 'MSF', 'MSL', 'MTEC', 'MTECU', 'MTGE', 'MXWL', 'MYND',
            'MZF', 'NANO', 'NAO', 'NAVG', 'NCI', 'NCOM', 'NDRO', 'NETS',
            'NITE', 'NNC', 'NRCG', 'NRE', 'NSU', 'NTC', 'NTRI', 'NVMM',
            'NXEO', 'NXEOU', 'NXTM', 'NYLD', 'NYNY', 'OAK', 'OHGI', 'OHRP',
            'OMED', 'ONEW', 'OPHT', 'ORBK', 'ORM', 'ORPN', 'OSIR', 'OSPRU',
            'P', 'PCMI', 'PERY', 'PETX', 'PGLC', 'PHIIQ', 'PHIKQ', 'PLLL',
            'PNTR', 'PRAN', 'PTIE', 'PTXTQ', 'PYDS', 'QCP', 'QSII', 'QTNA',
            'RDC', 'REN', 'RHT', 'RLM', 'RNN', 'ROX', 'RTEC', 'RVEN', 'RXII',
            'SCAC', 'SCACU', 'SFLY', 'SFS', 'SGYPQ', 'SHLM', 'SHOS', 'SHPG',
            'SIFI', 'SIR', 'SKIS', 'SLD', 'SMSH', 'SPA', 'SSFN', 'STLR',
            'STNL', 'STNLU', 'SVU', 'SXCP', 'TAHO', 'TFCF', 'TFCFA', 'TIER',
            'TISA', 'TLP', 'TMCX', 'TMCXU', 'TOWR', 'TPIV', 'TRCO', 'TRK',
            'TRNC', 'TSS', 'TST', 'TYPE', 'UBNK', 'UBNT', 'UCBA', 'ULTI',
            'UQM', 'USG', 'UWN', 'VEACU', 'VICL', 'VMAX', 'VSAR', 'VSM',
            'WAGE', 'WGP', 'WP', 'XGTI', 'XRM', 'XSPL', 'ZDEO', 'ZF', 'ZJBR',
            'CVON', 'FFKT', 'KLXI', 'HNTUF', 'EGLTQ', 'NEWM', 'HCLP', 'HDP',
            'GSTCQ', 'DFBHU', 'ILG', 'MATR', 'RENX', 'VLP', 'TSRO', 'IMPV',
            'XL', 'FNBG', 'WSCI', 'COTV', 'CVRR', 'RSYS', 'VCOYY', 'JMBA',
            'FCB', 'ATAC', 'JHA', 'EEP', 'STBZ', 'GPT', 'APB', 'BPK', 'PRTHU',
            'VVC', 'APTI', 'PF', 'ENLK', 'CWAY', 'BBOX', 'ABAX', 'JTPY',
            'ARMO', 'ESIO', 'HQCL', 'ESND', 'EMJ', 'NYRT', 'AVDR', 'SNMX',
            'SVA', 'DNJR', 'RLJE', 'CQH', 'TBLTU', 'ANCX', 'PNK', 'EGC',
            'CHFN', 'DCT', 'XPLR', 'ESRX', 'EIO', 'DM', 'OCIP', 'STDY',
            'ATHN', 'TBRGU', 'BJZ', 'SEND', 'MCRN', 'EIA', 'MMV', 'ALOG',
            'DVMT', 'SYNT', 'EIP', 'XCRA', 'PAY', 'IPAS', 'COBZ', 'BRQS',
            'MIW', 'CAVM', 'GBNK', 'EMI', 'DGSE', 'DDR', 'ZGYH', 'CCAC',
            'ZGYHR']

# These stocks are shorts
SHORTS = ['BIS', 'CROC', 'DDG', 'DOG', 'DPK', 'DRIP', 'DUG', 'DUST', 'DXD',
          'EDZ', 'EEV', 'EFU', 'EFZ', 'ERY', 'EUM', 'EUO', 'EWV', 'FAZ',
          'FINZ', 'FXP', 'GASX', 'GLL', 'KOLD', 'LABD', 'MIDZ', 'MYY', 'MZZ',
          'OILD', 'PSQ', 'PST', 'QID', 'REK', 'REW', 'RUSS', 'RWM', 'RXD',
          'SAGG', 'SBB', 'SBM', 'SCC', 'SCO', 'SDD', 'SDOW', 'SDP', 'SDS',
          'SEF', 'SH', 'SIJ', 'SJB', 'SMDD', 'SMN', 'SOXS', 'SPXS', 'SPXU',
          'SQQQ', 'SRS', 'SRTY', 'SSG', 'SVXY', 'SZK', 'TBF', 'TBT', 'TBX',
          'TECS', 'TMV', 'TTT', 'TWM', 'TYBS', 'TYNS', 'TYO', 'TZA', 'UDN',
          'YCS', 'YXI', 'ZBIO', 'ZSL', 'BNKD', 'BNKZ', 'DFVS', 'DGAZ', 'DGLD',
          'DLBR', 'DLBS', 'DRR', 'DSLV', 'DTUS', 'DTYS', 'DWT', 'EXIV', 'FLAT',
          'FNGD', 'FNGZ', 'GNAF', 'KNAB', 'NRGD', 'NRGZ', 'TAPR', 'WTID',
          'XXVFF', 'YGRN', 'ZIV', 'BZQ', 'TVIX', 'UVXY', 'EPV', 'FTSD', 'VIXY',
          'UVXY']

EXCLUSIONS = DELISTED + SHORTS

# Symbols can not be found from stocktwits
STOCKTWITS_NOT_FOUND = ['MMTM', 'SPSM', 'SPMB', 'SPSB', 'PPLC', 'DRTT', 'FCOR',
                        'SPEM', 'SYG', 'USFR', 'TFLO', 'JPGE', 'QMCO', 'SPGP',
                        'QSY', 'LOWC', 'J', 'SYE', 'COFS', 'DIVA', 'SPAB',
                        'SYV', 'CHIC', 'SVC', 'SPLB', 'SPTL', 'OPCH', 'ROUS',
                        'TIIAY', 'MDRIQ', 'SPTS', 'THTX', 'SPIB', 'BBC', 'VEGA',
                        'MNSB', 'HDG', 'GQRE', 'IQDE', 'PFIG', 'EEMA', 'BDCS',
                        'FTSD', 'FRPH', 'WBII', 'IBDL', 'HSPX', 'BSCL', 'IBMI',
                        'PBBI', 'JMLP', 'EQNR', 'IBDC', 'FWONA', 'IPKW', 'FNDA',
                        'NEPH', 'XSOE', 'TSLF', 'RAVI', 'DBEU', 'HYLS', 'WBIG',
                        'ISTB', 'AIRR', 'ACWV', 'FLN', 'TILT', 'HUSE', 'FTLS',
                        'IUSV', 'CHMG', 'LTRPA', 'EEMS', 'RDVY', 'XSLV', 'PGHY',
                        'CFO', 'NIQ', 'SZC', 'CIL', 'USRT', 'EFAD', 'IGSB',
                        'FNY', 'IQLT', 'IPFF', 'HYGH', 'SPVM', 'FNDX', 'TLTD',
                        'AIF', 'SMBK', 'BSJL', 'GAL', 'CEZ', 'LQDH', 'BBDC',
                        'CRBN', 'ATEX', 'ARDC', 'SUSA', 'FNDF', 'EWGS', 'FTLB',
                        'ICMB', 'AGZD', 'CMCT', 'DBEZ', 'BSJK', 'EWSC', 'ESBA',
                        'FYLD', 'FRG', 'TOLZ', 'HEFA', 'PTVCB', 'ICSH', 'BANX',
                        'HYMB', 'GAA', 'RINF', 'RDIV', 'IEUR', 'IGLB', 'IQDF',
                        'DBAW', 'CSB', 'ROOF', 'CFA', 'BCM', 'VUSE', 'CBH',
                        'ARGO', 'MDIV', 'FDT', 'FTSM', 'FLRN', 'FGM', 'EELV',
                        'MRIC', 'FEUZ', 'IGHG', 'DGRS', 'MVBF', 'MBSD', 'MELR',
                        'IUSB', 'BSCN', 'SAMG', 'TTSH', 'RGT', 'IBCD', 'NDP',
                        'BGB', 'CSF', 'SPXC', 'FKU', 'EDOG', 'QWLD', 'LGLV',
                        'EMLP', 'FEMB', 'OCSL', 'EFF', 'FEMS', 'MINC', 'TLTE',
                        'DGRE', 'HYHG', 'LMBS', 'CATC', 'EQAL', 'IMTM', 'FPXI',
                        'AMU', 'EMHY', 'VIDI', 'FJP', 'UE', 'KBWR', 'FSZ', 'RLY',
                        'JPMV', 'IEUS', 'FNK', 'SJNK', 'EWUS', 'LXFR', 'SNLN',
                        'BWG', 'CARE', 'FLGE', 'CXP', 'EQWL', 'IDOG', 'ULST',
                        'JPXN', 'BSJM', 'QEFA', 'EUMV', 'BSCK', 'XMLV', 'WDIV',
                        'GL', 'QDYN', 'FTGC', 'EWMC', 'IPAC', 'BBAR', 'BSCM',
                        'BYLD', 'CAPE', 'CCEP', 'CDC', 'CEMB', 'CIZ', 'CLDB',
                        'CMCL', 'COMT', 'DBLV', 'DKL', 'DSE', 'DVYA', 'DWAS',
                        'EDEN', 'EINC', 'EMCG', 'ENOR', 'ESXB', 'EUDG', 'FBGX',
                        'FBND', 'FBZ', 'FDTS', 'FEM', 'FILL', 'FMBH', 'FMNB',
                        'FNDC', 'FNWB', 'FRAF', 'FRBA', 'FTHI', 'FTSL', 'GGZ',
                        'GHYG', 'HBMD', 'HECO', 'HEEM', 'HEWJ', 'HOLD', 'HYXU',
                        'IDHQ', 'IDLV', 'IFV', 'IGIB', 'ILTB', 'INBK', 'INCO',
                        'INSI', 'ISTR', 'JMM', 'JPEM', 'JPIN', 'KBAL', 'KFYP',
                        'LCNB', 'MBCN', 'MLPC', 'NFRA', 'NMS', 'NTUS', 'NXTG',
                        'PFIS', 'PIPR', 'QDF', 'QEMM', 'QLTA', 'RBNC', 'RIGS',
                        'RVNU', 'SDG', 'SLCT', 'SMDV', 'SMEZ', 'SMLV', 'SRLN',
                        'SUZ', 'TDTT', 'UAE', 'VLU', 'VTIP', 'VWOB', 'XAN',
                        'ZJPN', 'AUB', 'BSCO', 'BTT', 'FDIV', 'FIBR', 'FLTB',
                        'FMB', 'ICOL', 'LEMB', 'RELX', 'XSMO', 'XSVM', 'AUOTY',
                        'FTS', 'INKM', 'IQDY', 'TIPX', 'XMVM', 'FIV', 'SLQD',
                        'USIG', 'FSBW', 'REGL', 'SPTM', 'AMCR', 'CDOR', 'CLSK',
                        'DBEM', 'EPAC', 'FHI', 'FNDE', 'HIE', 'HLIO', 'HYND',
                        'MLPO', 'OLEM', 'SFBC', 'TDTF', 'URTH', 'WBIE', 'XHS',
                        'VBND', 'BFOR', 'ENFR', 'EUSC', 'FNDB', 'IMLP', 'ROAM',
                        'SPLG', 'SSPY', 'WBIF', 'WBIL', 'BLU', 'DHC', 'FMK',
                        'FNCB', 'MEAR', 'ATMP', 'EMIH', 'FDBC', 'TFII', 'VEGI',
                        'WEBK', 'AGND', 'IBCE', 'IBDD', 'FPA', 'GLOW', 'HYIH',
                        'IBDM', 'IBDN', 'IBDO', 'IBDP', 'IBDQ', 'MOM', 'PHDG',
                        'SPEX', 'CDMOP', 'CHSCO', 'CTV', 'CTY', 'DTQ', 'EAB',
                        'EEMO', 'ELU', 'EMFM', 'EUFX', 'FITBI', 'MFO', 'NYMTP',
                        'PPX', 'QED', 'SDEM', 'TCBIL', 'UZA', 'ZCAN', 'ZIONP']
